name: Version Bump

on:
  push:
    branches:
      - main


jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest commit message
        id: commit
        run: echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bump
        run: |
          # Extract commit message
          COMMIT_MSG="${{ steps.commit.outputs.msg }}"
          VERSION_FILE="VERSION"

          # Get current version (default 0.0.0 if no file exists yet)
          if [ -f "$VERSION_FILE" ]; then
            VERSION=$(cat $VERSION_FILE)
          else
            VERSION="0.0.0"
          fi

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          if [[ "$COMMIT_MSG" == major:* ]]; then
            MAJOR=$((MAJOR+1))
            MINOR=0
            PATCH=0
          elif [[ "$COMMIT_MSG" == feat:* ]]; then
            MINOR=$((MINOR+1))
            PATCH=0
          elif [[ "$COMMIT_MSG" == fix:* ]]; then
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo $NEW_VERSION > $VERSION_FILE
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit & Push version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add VERSION
          git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}"
          git push

      - name: Create Git tag
        run: |
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin v${{ steps.bump.outputs.new_version }}
